# Generated by Django 3.0.7 on 2020-08-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='company_name',
            new_name='business_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_manufacturer',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
